export const status = [
  {
    id: "1",
    active: true,
    cancelled: false,
    pending: false,
    droppedOut: false,
    slug: "1111",
  },
  {
    id: "2",
    active: false,
    cancelled: true,
    pending: false,
    droppedOut: false,
    slug: "2222",
  },
  {
    id: "3",
    active: false,
    cancelled: false,
    pending: true,
    droppedOut: false,
    slug: "3333",
  },
  {
    id: "4",
    active: false,
    cancelled: false,
    pending: false,
    droppedOut: true,
    slug: "4444",
  },
  {
    id: "5",
    active: true,
    cancelled: false,
    pending: false,
    droppedOut: false,
    slug: "5555",
  },
  {
    id: "6",
    active: false,
    cancelled: true,
    pending: false,
    droppedOut: false,
    slug: "6666",
  },
  {
    id: "7",
    active: false,
    cancelled: false,
    pending: true,
    droppedOut: false,
    slug: "7777",
  },
  {
    id: "8",
    active: false,
    cancelled: false,
    pending: false,
    droppedOut: true,
    slug: "8888",
  },
  {
    id: "9",
    active: true,
    cancelled: false,
    pending: false,
    droppedOut: false,
    slug: "9999",
  },
  {
    id: "10",
    active: false,
    cancelled: true,
    pending: false,
    droppedOut: false,
    slug: "1010",
  },
];
